[env]
RUST_LOG = "info"

[global]
bin = '../target/release/create_posting_mdata'
# input-path = '{RISE_DATA_DIR}/ccnews/ccnews.bin'
input-path = '{RISE_DATA_DIR}/ccnews/ccnews.bin.rgb'

# Starting from here each section is an experiment -------------------

[mdata.static]
out-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'
block-size = 128

# [mdata.variable]
# out-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'
# variable-block = ""
# lambda = 12.0
