[env]
RUST_LOG = "info"

[global]
bin = '../target/release/create_posting_mdata'
# input-path = '{RISE_DATA_DIR}/clueweb/clueweb.bin'
input-path = '{RISE_DATA_DIR}/clueweb/clueweb.bin.rgb'

# Starting from here each section is an experiment -------------------

[mdata.static]
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.static.mdata'
block-size = 128

[mdata.variable]
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.var.mdata'
variable-block = ""
lambda = 12.0
