[env]
RUST_LOG = "info"

[global]
bin = '../target/release/build_index'
# input-path = '{RISE_DATA_DIR}/clueweb/clueweb.bin'
input-path = '{RISE_DATA_DIR}/clueweb/clueweb.rgb.bin'

# Starting from here each section is an experiment -------------------

[bic.build]
idx-kind = 'block_interpolative'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.bic.idx'

[vbyte.build]
idx-kind = 'block_vbyte'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.vbyte.idx'

[ef.build]
idx-kind = 'ef'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.ef.idx'

[upef.build]
idx-kind = 'upef'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.upef.idx'

[opt.build]
idx-kind = 'opt'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.opt.idx'

[optcomp.build]
idx-kind = 'optcomp'
out-path = '{RISE_DATA_DIR}/built_indexes/cw09.rgb.optcomp.idx'
