#sets environment variables
[env]
RUST_LOG = "info"

# These arguments will be used in all further experiments, if not redefined in each section
# In particular, `bin` is the path of the binary that will be run
[global]
bin = '../target/release/build_index'
# input-path = '/data1/InvertedIndexes/inverted_indexes/gov2/gov2.sorted-text.bin'
input-path = '/data1/InvertedIndexes/inverted_indexes/gov2/gov2.rgb.bin'

# Starting from here each section is an experiment -------------------

# [ef.build]
# idx-kind = 'ef'
# out-path = '/data1/InvertedIndexes/built_indexes/pef/gov2.ef.pef.out'

[upef.build]
idx-kind = 'upef'
out-path = '/data1/InvertedIndexes/built_indexes/pef/gov2.upef.pef.out'

# [opt.build]
# idx-kind = 'opt'
# out-path = '/data1/InvertedIndexes/built_indexes/pef/gov2.opt.pef.out'

# [optcomp.build]
# idx-kind = 'optcomp'
# out-path = '/data1/InvertedIndexes/built_indexes/pef/gov2.rgb.optcomp.pef.out'
