#sets environment variables
[env]
RUST_LOG = "info"

# These arguments will be used in all further experiments, if not redefined in each section
# In particular, `bin` is the path of the binary that will be run
[global]
bin = '../target/release/query'

query-path = '/data1/InvertedIndexes/inverted_indexes/ccnews/05.efficiency_queries.mapped'

n-runs = 2
n-queries = 1000

# Starting from here each section is an experiment -------------------

# SINGLE EF -----------------------------------------

[ef]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.ef.pef.out'
index-kind = 'ef'

[ef.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[ef.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[ef.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.var.mdata'

# UNIFORM PARTITIONING EXPERIMENTS -------------------

[up]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.upis.pef.out'
index-kind = 'upis'

[up.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[up.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[up.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.var.mdata'

# OPT ----------------------------------------------------

[opt]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.upis.pef.out'
index-kind = 'upis'

[opt.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[opt.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.static.mdata'

[opt.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cc_url.var.mdata'
