#sets environment variables
[env]
RUST_LOG = "info"

# These arguments will be used in all further experiments, if not redefined in each section
# In particular, `bin` is the path of the binary that will be run
[global]
bin = '../target/release/query'

query-path = '{RISE_DATA_DIR}/ccnews/ccnews.queries'

n-runs = 2
n-queries = 1000

# Starting from here each section is an experiment -------------------

# SINGLE EF -----------------------------------------

[ef]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.ef.idx'
index-kind = 'ef'

[ef.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[ef.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[ef.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'

# UNIFORM PARTITIONING EXPERIMENTS -------------------

[up]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.upef.idx'
index-kind = 'upef'

[up.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[up.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[up.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'

# OPT ----------------------------------------------------

[opt]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.opt.idx'
index-kind = 'opt'

[opt.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[opt.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[opt.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'

# BIC -----------------------------------------

[bic]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.bic.idx'
index-kind = 'block_interpolative'

[bic.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[bic.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[bic.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'


# SVB -----------------------------------------

[svb]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.vbyte.idx'
index-kind = 'block_vbyte'

[svb.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[svb.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[svb.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'

# OPTCOMP -----------------------------------------

[optcomp]
index-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.optcomp.idx'
index-kind = 'optcomp'

[optcomp.cc_url]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[optcomp.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.static.mdata'

[optcomp.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '{RISE_DATA_DIR}/built_indexes/ccnews.rgb.var.mdata'
