[env]
RUST_LOG = "info"

[global]
bin = '../target/release/query'

query-path = '/data1/InvertedIndexes/inverted_indexes/clueweb09/clueweb.sorted-text.queries0.mapped'

n-runs = 2
n-queries = 1000

# EF -----------------------------------------

[ef]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.ef.pef.out'
index-kind = 'ef'

[ef.cw09]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[ef.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[ef.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.var.mdata'

# UNIFORM PARTITIONING EXPERIMENTS -------------------

[up]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.upis.pef.out'
index-kind = 'upis'

[up.cw09]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[up.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[up.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.var.mdata'

# OPT ----------------------------------------------------

[opt]
index-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.opt.pef.out'
index-kind = 'opt'

[opt.cw09]
query-kind = ['boolean-and', 'ranked-and', 'ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[opt.blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[opt.blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.var.mdata'
