[env]
RUST_LOG = "info"

[global]
bin = '../target/release/query'
index-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.opt.pef.out'
index-kind = 'opt'

query-path = '/data1/InvertedIndexes/inverted_indexes/clueweb09/clueweb.sorted-text.queries0.mapped'

n-runs = 2
n-queries = 1000

[cw09]
query-kind = ['ranked-or', 'wand', 'maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[blockmax_static]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.static.mdata'

[blockmax_variable]
query-kind = ['bm-wand', 'bm-maxscore']
meta-path = '/data1/InvertedIndexes/built_indexes/pef/cw09.var.mdata'
