[env]
RUST_LOG="info"

[global]
bin='../target/release/query'
index-path='/data1/InvertedIndexes/built_indexes/pef/gov2.ef.pef.out'
index-kind='ef'

query-path='/data1/InvertedIndexes/inverted_indexes/gov2/gov2.sorted-text.queries0.mapped'

n-runs=2
n-queries=1000

[gov2]
query-kind=['wand','maxscore']
meta-path='/data1/InvertedIndexes/built_indexes/pef/gov2.static.mdata'

[blockmax_static]
query-kind=['bm-wand','bm-maxscore']
meta-path='/data1/InvertedIndexes/built_indexes/pef/gov2.static.mdata'

[blockmax_variable]
query-kind=['bm-wand','bm-maxscore']
meta-path='/data1/InvertedIndexes/built_indexes/pef/gov2.var.mdata'
