[env]
RUST_LOG = "info"

[global]
bin = '../target/release/read_write_rgb'

# Starting from here each section is an experiment -------------------

[cw09.rgb]
input-path = '{RISE_DATA_DIR}/clueweb/clueweb.bin'
out-path = '{RISE_DATA_DIR}/clueweb/clueweb.bin.rgb'

[ccnews.rgb]
input-path = '{RISE_DATA_DIR}/ccnews/ccnews.bin'
out-path = '{RISE_DATA_DIR}/ccnews/ccnews.bin.rgb'
